
modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/vectorwing/FarmersDelight/issues"
license="MIT License"

[[mods]]
modId="farmersdelight"
version="1.15.2-0.2.3"
displayName="Farmer's Delight"
# updateJSONURL=""
displayURL="https://github.com/vectorwing/FarmersDelight"
logoFile="logo.png"
logoBlur=false
credits="Chloe Dawn, simibubi, Silk, SkySom and many other wonderful people!"
authors="vectorwing, Grimmauld"
description="A lightweight farming expansion. Harvest, cook and explore!"
[[dependencies.farmersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.12,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.farmersdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
