
modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/vectorwing/FarmersDelight/issues"
license="MIT License"

[[mods]]
modId="farmersdelight"
version="1.16.1-0.2.2a"
displayName="Farmer's Delight"
# updateJSONURL=""
displayURL="https://github.com/vectorwing/FarmersDelight"
logoFile="logo.png"
logoBlur=false
credits="Chloe Dawn, simibubi, Silk, SkySom and many other wonderful people!"
authors="vectorwing, Grimmauld"
description="A lightweight farming expansion for Minecraft. Harvest, cook and explore!"

[[dependencies.farmersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.farmersdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
